# Generated by Django 3.0.6 on 2020-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=200)),
                ('origin', models.TextField(default=True)),
                ('description', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=200)),
                ('gender', models.CharField(default=True, max_length=200)),
                ('date_of_birth', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField(default=True)),
                ('breed', models.CharField(default=True, max_length=200)),
                ('owner', models.CharField(default=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=200)),
                ('adress', models.TextField(default=True)),
                ('house_type', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=200)),
                ('gender', models.CharField(default=True, max_length=200)),
                ('date_of_birth', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField(default=True)),
                ('home', models.IntegerField(default=True)),
            ],
        ),
    ]
