# Generated by Django 3.0.7 on 2020-06-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('origin', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True)),
                ('house_type', models.CharField(choices=[('Landed', 'Landed'), ('Condominium', 'Condominium')], default='Landed', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default=None, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catwiki.Home')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default=None, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catwiki.Breed')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catwiki.Human')),
            ],
        ),
    ]
