# Generated by Django 3.0.7 on 2020-06-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki', '0002_home_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='slug',
        ),
    ]
