# Generated by Django 3.0.7 on 2020-06-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catwiki', '0004_home_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
